### ISSUE TITLE
Use `mdast-util-directive`

### ISSUE THREAD

**Issue by alvinometric** [ipikuka/remark-flexible-containers#1]
Hello! 
Thanks for the plugin. There is an official extension for directives (which are the same `:::` syntax.): [`mdast-util-directive`](https://github.com/syntax-tree/mdast-util-directive)

Would it be better to use it rather than doing the parsing in this plugin ?

**Comment by talatkuyuk** [comment]
[mdast-util-directive](https://github.com/syntax-tree/mdast-util-directive) is more generic remark plugin for producing flexible nodes including containers and others.

But, the [remark-flexible-containers](https://github.com/ipikuka/remark-flexible-containers) is more opinionated remark plugin for creating containers. It is up to you which one is your preference. 

I suggest you to use my plugin since it has additional capabilities / options for making containers.
